# This is a basic workflow to help you get started with Actions
 
name:
  Choose random song
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every midnight
  schedule:
    - cron: "0 0 * * *"
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Choose-song
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://heardle-peach.vercel.app/api/cron'
        method: 'POST'
